### ISSUE TITLE
Missing event classes in package io.plumery.inventoryitem.core.events

### ISSUE THREAD

**Issue by ractive** [vgoldin/cqrs-eventsourcing-kafka#2]
I just checkout out your project to browse through the code and it seems as if the package `io.plumery.inventoryitem.core.events` with all its event classes is missing. Would be nice if you could add them.

**Comment by vgoldin** [comment]
events and commands are generated from JSON schema as part of the build process. please do `mvn clean install`

**Comment by ractive** [comment]
Ah I see. Thanks for the info.

**Comment by chonianxi** [comment]
How run in IntelliJ IDEA ,io.plumery.inventoryitem.core.events is not found
